#!/bin/sh
# If you use Konsole in KDE4 and want the peaksea dark color in 16-color mode, 
# run this script

mkdir -p ~/.kde/share/apps/konsole
cp PeakSeaDark.colorscheme ~/.kde/share/apps/konsole/PeakSeaDark.colorscheme
